version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    executor: ruby/default
    steps:
      - name: checkout
      - checkout

      - name: install dependencies
        run: |
        gem install bundler

      - name: test application
        run: |
        rake spec