version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
    steps:
      - checkout
      - run:
          command: gem install bundler

      - run:
          command: bundle install

      - run:
          name: test
          command: rake spec